[package]
name = "project-ng"
version = "0.1.0"
edition = "2021"

# disable stack unwinding on panic
[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.9.23"
